sonar.projectKey=CraigHall-gmail_MyApi
sonar.organization=craighall-gmail
sonar.qualitygate.wait=true
sonar.cs.cobertura.reportPaths=**/TestResults/**/coverage.cobertura.xml
sonar.cs.vstest.reportsPaths=**/*.trx
