name: development - Platform Deploy

on:
  push:
    branches: [development]
    paths:
      - 'infra/development/**'
  pull_request:
    paths:
      - 'infra/development/**'
  workflow_dispatch:
    inputs:
      destroy:
        description: "Destroy resources?"
        type: boolean
        default: false

concurrency:                              
  group: terraform-${{ github.ref }}
  cancel-in-progress: false
  
permissions:          
  id-token: write
  contents: read
  pull-requests: write
  
jobs:
  deploy:
    uses: ./.github/workflows/_shared-aca-dev.yml
    with:
      environment:               development
      working_directory:         infra/development
      tf_version:                "1.8.0"
      destroy:                   ${{ inputs.destroy || false }}
      tf_state_storage_account:  myapiterraformstate
      tf_state_container:        tfstate
      tf_state_key:              development/api.tfstate
    secrets:
      AZURE_CLIENT_ID:        ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID:        ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
